CREATE TABLE [dbo].[Category] (
    [Id]           INT          IDENTITY (1, 1) NOT NULL,
    [CategoryName] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

SET IDENTITY_INSERT [dbo].[Category] ON
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (22, N'REFRIGERATOR')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (23, N'MICRO OVEN')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (24, N'WASHING MACHINE POWER')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (25, N'PLASTIC FURNITURE')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (26, N'STOVE (CHOOLA)')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (27, N'CELLING FAN')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (28, N'STAND FAN')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (29, N' BLANDER/ JUSAR')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (30, N'STABLIZER')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (31, N'REFREGERATOR Electroiux')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (32, N'REFREGERATOR Electroiux')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (34, N'REFREGERATOR KOMBO ')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (35, N'DEEP FREEZERS TRIPLET')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (36, N'ORIENT')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (37, N'SINGER')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (38, N'WASHING MACHINE WAVES DOUBEL')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (39, N'WASHING MACHINE ZEBO')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (40, N'WASHING MACHIN Super ASIA')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (42, N'IRON-ISTRY')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (43, N'GEZAR PK')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (44, N'PEDESTAL FAN')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (45, N'PEL REFRIGERATOR')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (46, N'REFREGERATOR PASSION GLASS')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (47, N'PEL-WASHING')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (48, N'HETAR  BEJLI')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (49, N'VISI  COOLER')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (50, N'juart ')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (51, N'sdfsdf')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (52, N'another model')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (53, N'just another')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (54, N'excuse me')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (55, N'just chil phil')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (56, N'ksdfasdfasdf')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (57, N'sdfasd')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (58, N'cgdfgdf')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (59, N'shakel')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (60, N'khallee')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (61, N'ok fine')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (62, N'Another Category')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (63, N'jososos')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (64, N'New Category')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (65, N'Here we go')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (66, N'ok')
INSERT INTO [dbo].[Category] ([Id], [CategoryName]) VALUES (67, N'new category')
SET IDENTITY_INSERT [dbo].[Category] OFF
