//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerContacts = new HashSet<CustomerContact>();
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.Guarantors = new HashSet<Guarantor>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage ="Please enter customer name")]
        [StringLength(29,ErrorMessage ="Please enter a valid customer name.")]
        [Display(Name ="Customer Name")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Please enter father name")]
        [StringLength(29, ErrorMessage = "Please enter a valid father name.")]
        [Display(Name = "Father Name")]
        public string FatherName { get; set; }

        [Required(ErrorMessage = "Please enter NIC number")]
        [StringLength(19, ErrorMessage = "Please enter a valid NIC number.")]
        [Display(Name = "NIC Number")]
        public string NIC { get; set; }

        [Required(ErrorMessage = "Please enter address.")]
        [StringLength(99, ErrorMessage = "Please enter a valid address.")]
        [Display(Name = "Address")]
        public string PrimaryAddress { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerContact> CustomerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guarantor> Guarantors { get; set; }
    }
}
