//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrder()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderPayments = new HashSet<OrderPayment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> GuarantorId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int MonthlyInstallment { get; set; }
        public System.DateTime DueDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Guarantor Guarantor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
