//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guarantor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guarantor()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }

        [Required(ErrorMessage  = "Pleae enter guarantor name.")]
        [StringLength(29, ErrorMessage = "Please enter valid guarantor name.")]
        [Display(Name = "Guarantor")]
        public string GuarantorName { get; set; }
        [Required(ErrorMessage  = "Pleae enter NIC number.")]
        [StringLength(19, ErrorMessage = "Please enter valid NIC number.")]
        [Display(Name = "NIC Number")]
        public string NIC { get; set; }
        [Required(ErrorMessage  = "Pleae enter contact number.")]
        [StringLength(19, ErrorMessage = "Please enter valid contact number.")]
        [Display(Name = "Contact")]
        public string Contact { get; set; }

        [Required(ErrorMessage  = "Pleae enter address.")]
        [StringLength(29, ErrorMessage = "Please enter valid address.")]
        [Display(Name = "Address")]
        public string PrimaryAddress { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
