//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }

        [Required(ErrorMessage  = "Pleae enter purchase price.")]
        [Range(1,999999999, ErrorMessage = "Please enter valid purchase price.")]
        [Display(Name = "Purchase Price")]
        public int PurchasePrice { get; set; }
        [Required(ErrorMessage  = "Pleae enter sale price.")]
        [Range(1, 999999999, ErrorMessage = "Please enter valid sale price.")]
        [Display(Name = "Sale Price")]
        public int SalePrice { get; set; }

        [Required(ErrorMessage  = "Pleae enter quantity.")]
        [Range(1, 999999999, ErrorMessage = "Please enter valid quantity.")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Range(0, 999999999, ErrorMessage = "Please enter valid discount.")]
        [Display(Name = "Discount")]
        public int Discount { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
