//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderPayment
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string UserId { get; set; }

        [Required(ErrorMessage  = "Pleae enter amount.")]
        [Range(1, 999999999, ErrorMessage = "Please enter valid amount.")]
        [Display(Name = "Amount")]
        public int AmountPaid { get; set; }
        public System.DateTime DatePaid { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
