//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.SupplyDetails = new HashSet<SupplyDetail>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Please Select a Category")]
        public Nullable<int> CategoryId { get; set; }
        [Required(ErrorMessage  = "Pleae enter model.")]
        [StringLength(29, ErrorMessage = "Please enter valid model.")]
        [Display(Name = "Model")]
        public string Model { get; set; }

        [Required(ErrorMessage  = "Pleae enter guarantee/warantee.")]
        [StringLength(99, ErrorMessage = "Please enter valid guarantee/warantee.")]
        [Display(Name = "Guarantee/Warantee")]
        public string GuaranteeWarranty { get; set; }

        [Required(ErrorMessage  = "Pleae enter purchase price.")]
        [Range(0,999999999, ErrorMessage = "Please enter valid purchase price.")]
        [Display(Name = "Purchase Price")]
        public int PurchasePrice { get; set; }

        [Required(ErrorMessage  = "Pleae enter sale price.")]
        [Range(0, 999999999, ErrorMessage = "Please enter valid sale price.")]
        [Display(Name = "Sale Price")]
        public int SalePrice { get; set; }

        [Required(ErrorMessage  = "Pleae enter installment ratio.")]
        [Range(0, 1, ErrorMessage = "Please enter valid installment ratio.")]
        [Display(Name = "Installment Ratio")]
        public double InstallmentRatio { get; set; }

        [Required(ErrorMessage  = "Pleae enter first payment ratio.")]
        [Range(0, 1, ErrorMessage = "Please enter valid first payment ratio.")]
        [Display(Name = "First Payment Ratio")]
        public double FirstPaymentRatio { get; set; }

        [Display(Name ="Installment Price")]
        public double InstallmentPrice { get; set; }
        [Display(Name ="First Payment")]
        public double FirstPayment { get; set; }

        [Required(ErrorMessage  = "Pleae enter number of months.")]
        [Range(1, 120, ErrorMessage = "Please enter valid number of months.")]
        [Display(Name = "Number of Months")]
        public int NoOfMonths { get; set; }
        public double MonthlyPayment { get; set; }

        [Required(ErrorMessage  = "Pleae enter quantity.")]
        [Range(0, 999999999, ErrorMessage = "Please enter valid quantity.")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyDetail> SupplyDetails { get; set; }
    }
}
