//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.SupplyDetails = new HashSet<SupplyDetail>();
            this.SupplyPayments = new HashSet<SupplyPayment>();
            
        }
    
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string UserId { get; set; }

        [Display(Name ="Supply Date")]
        [DisplayFormat(DataFormatString = "{0:ddd,dd MMM yyyy}")]
        public System.DateTime SupplyDate { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyDetail> SupplyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyPayment> SupplyPayments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
