//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.SupplierAccounts = new HashSet<SupplierAccount>();
            this.SupplierContacts = new HashSet<SupplierContact>();
            this.Supplies = new HashSet<Supply>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage  = "Pleae enter suppler name.")]
        [StringLength(29, ErrorMessage = "Please enter valid supplier name.")]
        [Display(Name = "Supplier Name")]
        public string SupplierName { get; set; }

        [Required(ErrorMessage  = "Pleae enter company.")]
        [StringLength(29, ErrorMessage = "Please enter valid company.")]
        [Display(Name = "Company")]
        public string Company { get; set; }

        [Required(ErrorMessage  = "Pleae enter address.")]
        [StringLength(99, ErrorMessage = "Please enter valid address.")]
        [Display(Name = "Address")]
        public string PrimaryAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierAccount> SupplierAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierContact> SupplierContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supplies { get; set; }
    }
}
