//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SupplyDetail
    {
        public int Id { get; set; }
        public Nullable<int> SupplyId { get; set; }
        public Nullable<int> ProductId { get; set; }

        [Display(Name ="Purchase Price")]
        [Required(ErrorMessage="Please enter purchase price.")]
        [Range(minimum:1,maximum:999999999,ErrorMessage ="Please enter valid purchase price.")]
        public int PurchasePrice { get; set; }

        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Please enter quantity.")]
        [Range(minimum: 1, maximum: 999999999, ErrorMessage = "Please enter valid quantity.")]
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
