//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaveedElectronicWeb.NEModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SupplierAccount
    {
        public int Id { get; set; }
        [Required(ErrorMessage  = "Pleae enter  account title.")]
        [StringLength(14, ErrorMessage = "Please enter valid acccount title.")]
        [Display(Name = "Account Title")]
        public string AccountTitle { get; set; }

        [Required(ErrorMessage = "Pleae enter  account number.")]
        [StringLength(24, ErrorMessage = "Please enter valid acccount number.")]
        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
